blog/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from blog import views

app_name='blog'
urlpatterns = [
    path('', views.PostListView.as_view()),
    path('posts', views.PostListView.as_view(), name='all'),
    path('posts/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('posts/create',
         views.PostCreateView.as_view(success_url=reverse_lazy('blog:all')), name='post_create'),
    path('posts/<int:pk>/update',
         views.PostUpdateView.as_view(success_url=reverse_lazy('blog:all')), name='post_update'),
    path('posts/<int:pk>/delete',
         views.PostDeleteView.as_view(success_url=reverse_lazy('blog:all')), name='post_delete'),
    path('registration', views.RegistrationView.as_view(), name='registration'),
    path('tag/<int:pk>', views.TagDetailView.as_view(), name='tag'),
    path('tag/create',
         views.TagCreateView.as_view(success_url=reverse_lazy('blog:all')), name='tag_create'),
    path('post/<int:pk>/connect',
         views.PostConnectView.as_view(success_url=reverse_lazy('blog:all')), name='post_connect'),

]

simple_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from PIL import Image
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(validators=[MinLengthValidator(1, "Your message is empty.")])
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(blank=True, upload_to="images")
    tags = models.ManyToManyField('Tag', through="Tagging")

    def __str__(self):
        return self.title


class Tag(models.Model):
    tag = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.tag


class Tagging(models.Model):
    posts = models.ForeignKey('Post', on_delete=models.CASCADE)
    taggings = models.ForeignKey('Tag', on_delete=models.CASCADE)

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class Registration(UserCreationForm):

    class Meta:
        fields = ('username', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Name'

    def clean_name(self):
        name = self.cleaned_data['username']
        if User.objects.filter(username=name).exists():
            raise ValidationError("User already exists")
        return name

blog/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render
from datetime import timedelta
from django.utils import timezone
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from blog.models import Post, Tag, Tagging
from django.core.paginator import Paginator
from django.views.generic.edit import FormView
from blog.forms import Registration
from django.contrib.auth.models import User, AnonymousUser
from django.contrib.auth import authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q

class TagDetailView(DetailView):
    model = Post

    def get(self, request, *args, **kwargs):
        id = kwargs['pk']
        print('tag detail' + str(id))
        tags = Tag.objects.get(id=id)
        print(tags)
        posts = Post.objects.filter(tags__id=id)
        print(posts)
        return render(request, 'blog/tag_detail.html', {'tags': tags, 'post_list': posts})


class TagCreateView(CreateView):
    model = Tag
    fields = ['tag']


class PostConnectView(CreateView):
    model = Tagging
    fields = ['taggings']

    def form_valid(self, form):
        print('form_valid called')
        object = form.save(commit=False)
        id = self.kwargs['pk']
        object.posts_id=id
        object.save()
        print('finish')
        return super(CreateView, self).form_valid(form)




class PostDetailView(DetailView):
    model = Post

    def post(self, request):
        post = request.POST['post']
        tag = request.POST['tag']
        posts = Post.objects.create(post=post)
        tags, created = Tag.objects.get_or_create(tag=tag)
        tp = Tagging(posts=posts, taggings=tags)
        tp.save()
        return render(request, 'blog/post_detail.html')

    def get(self, request, *args, **kwargs):
        id = kwargs['pk']
        print(id)
        post = Post.objects.get(id=id)
        tags = post.tags.all()
        return render(request, 'blog/post_detail.html', {'tags_list': tags, 'post' : post})


class PostCreateView(CreateView):
    model = Post
    fields = ['title', 'text', 'image']

    def form_valid(self, form):
        print('form_valid called')
        object = form.save(commit=False)
        print(self.request.user)
        if self.request.user.is_authenticated:
            object.owner = self.request.user
        object.save()
        return super(CreateView, self).form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'text', 'image']

    def get_queryset(self):
        print('update get_queryset called')
        """ Limit a User to only modifying their own data. """
        qs = super(UpdateView, self).get_queryset()
        return qs.filter(owner=self.request.user)


class PostDeleteView(DeleteView):
    model = Post

    def get_queryset(self):
        print('delete get_queryset called')
        qs = super(DeleteView, self).get_queryset()
        return qs.filter(owner=self.request.user)


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        qs = super(ListView, self).get_queryset()
        return qs.order_by('created_at').reverse()[:10]

    def get(self, request, *args, **kwargs):
        post_list = Post.objects.all().order_by('created_at').reverse()
        paginator = Paginator(post_list, 10)  # Show 10 posts per page
        page = request.GET.get('page')
        stuff = paginator.get_page(page)
        return render(request, 'blog/post_list.html', {'post_list': stuff})


class RegistrationView(FormView):
    template_name = 'registration/registration.html'
    form_class = Registration
    success_url = 'posts'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        password = form.clean_password2()
        name = form.clean_name()
        user = authenticate(self.request, username=name, password=password)
        if user is None:
            us1 = User.objects.create_user(name, None, password)
            us1.save()
        else:
            print("User already exits!")
            raise ValidationError("User already exits!")
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

templates/blog/main.html
{% extends 'base.html' %}
{% block content %}
<p>
{% if user.is_authenticated %}
<p>Authenticated as
<pre>
Name: {{ user.get_full_name }}
Email: {{ user.email }}
Id: {{ user.id }}
</pre>
</p>
<p>You can <a href="/accounts/logout">Logout</a></p>
{% else %}
<p>You can <a href="/accounts/login">Login</a> if you like.</p>
{% endif %}
{% if islocal %}
Some of the samples will require a user login to be created.
</p>
{% endif %}
{% endblock %}

templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete post</h1>

<p>Are you sure you want to delete the post: {{ post.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" class="btn btn-success" value="Yes, delete.">
</form>
{% endblock %}

templates/blog/post_connect.html
{% extends 'base.html' %}
{% block content %}
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Submit">
    <input type="submit" class="btn btn-danger" value="Cancel" onclick="window.location.href='{% url 'blog:all' %}';return false;">
  </form>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
<span style="float: right;">
(Created at {{ post.created_at }}, updated at {{ post.updated_at }}, publication date {{ post.pub_date }})
    {% if message.owner == user %}
    <a href="{% url 'blog:message_update' post.id %}"><i class="fa fa-pencil"></i></a>
    <a href="{% url 'blog:message_delete' post.id %}"><i class="fa fa-trash"></i></a>
    {% endif %}
</span>

        <div class="jumbotron">
        <div class="media">
            <div class="media-left">
            {% if post.image %}
                <img src="{{ post.image.url }}" height="300" class="media-object">
            {% endif %}
            </div>
            <div class="media-body">
                <h2>{{ post.title }}</h2>
                <p>{{ post.text }}</p>
            </div>
        </div>

    <ul class="list-inline">
        {% for tag in tags_list %}
        <li>
            <a href="{% url 'blog:tag' tag.id %}">#{{ tag }}</a>
        </li>
        {% endfor %}
    </ul>
            </div>
    <p><a href="{% url 'blog:post_connect' post.id %}">Add tag</a></p>
    <p><a href="{% url 'blog:all' %}">All posts</a></p>
{% endblock %}

templates/blog/post_form.html
{% extends 'base.html' %}
{% block content %}
        <form action="" method="post" enctype="multipart/form-data">
            <div class="form-group">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-success" value="Submit">
                <input type="submit" class="btn btn-danger" value="Cancel" onclick="window.location.href='{% url 'blog:all' %}';return false;">
            </div>
        </form>
{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Posts</h1>
        {% if post_list %}
            <ul class="list-group">
                {% for post in post_list %}
                    <li class="list-group-item">
                        <a href="{% url 'blog:post_detail'  post.id %}">{{ post.title }} </a>
                        {% if post.image %}
                            <img src="{{ post.image.url }}" height="100">
                        {% endif %}
                        <span style="float: right;">{{ post.created_at }} </span>
                        <span style="float: right;">{{ post.owner }} --- </span>
                        {% if post.owner == user %}
                            (<a href="{% url 'blog:post_update' post.id %}">Edit</a> |
                            <a href="{% url 'blog:post_delete' post.id %}">Delete</a>)
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
            <div class="pagination">
                <span class="step-links">
                    {% if post_list.has_previous %}
                        <ul class="pager">
                            <li class="first"><a href="?page=1">&laquo; first</a></li>
                            <li class="previous"><a href="?page={{ post_list.previous_page_number }}">previous</a></li>
                        </ul>
                    {% endif %}
                    <span class="current">
                        Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.
                    </span>
                    {% if post_list.has_next %}
                        <ul class="pager">
                            <li class="next"><a href="?page={{ post_list.next_page_number }}">next</a></li>
                            <li class="last"><a href="?page={{ post_list.paginator.num_pages }}">last &raquo;</a></li>
                        </ul>
                    {% endif %}
                </span>
            </div>
        {% else %}
            <p>There are no posts in the database.</p>
        {% endif %}
        <ul class="list-group">
            <i><a href="{% url 'blog:post_create' %}">Add a post</a></i><br>
            <i><a href="{% url 'blog:tag_create' %}">Create a tag</a></i>
        </ul>
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}?next={% url 'blog:all' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}?next={% url 'blog:all' %}">Login</a> or
            <a href="{% url 'blog:registration' %}?next={% url 'blog:all' %}">Registration</a>
        {% endif %}
    </div>
{% endblock %}

templates/blog/tag_detail.html
{% extends 'base.html' %}
{% block content %}
    <p>#{{ tags }}</p>
    <ul class="list-group">
        {% for post in post_list %}
            <li class="list-group-item"><a href="{% url 'blog:post_detail'  post.id %}">{{ post.title }} </a>
                {% if post.image %}
                    <img src="{{ post.image.url }}" height="100">
                {% endif %}
                <span style="float: right;">{{ post.created_at }} </span>
                <span style="float: right;">{{ post.owner }} --- </span>
                {% if post.owner == user %}
                    (<a href="{% url 'blog:post_update' post.id %}">Edit</a> |
                    <a href="{% url 'blog:post_delete' post.id %}">Delete</a>)
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'blog:all' %}">All posts</a>
{% endblock %}

templates/blog/tag_form.html
{% extends 'base.html' %}
{% block content %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-success" value="Submit">
            <input type="submit" class="btn btn-danger" value="Cancel" onclick="window.location.href='{% url 'blog:all' %}';return false;">
        </form>
{% endblock %}

templates/blog/tagging_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Submit">
    <input type="submit" class="btn btn-danger" value="Cancel" onclick="window.location.href='{% url 'blog:all' %}';return false;">
  </form>
</div>
{% endblock %}